/*
  Copyright (C) 2002-2021 CERN for the benefit of the ATLAS collaboration
*/

#ifndef TFCSSimulationRun_H
#define TFCSSimulationRun_H

#include "ISF_FastCaloSimEvent/TFCSParametrizationBase.h"
#include "ISF_FastCaloSimEvent/TFCSSimulationState.h"

/**
 * @class TFCSSimulationRun
 * @brief Represents a simulation run in the TFCSSimulation framework
 * @details This class provides methods for accessing and manipulating simulation runs
 * @ingroup TFCSSimulation
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
class TFCSSimulationRun: public TNamed
{
public:
  TFCSSimulationRun(const char* name=0, const char* title=0):TNamed(name,title),m_basesim(0),m_simul(0) {};
  TFCSSimulationRun(const char* name, const char* title,TFCSParametrizationBase* ref):TNamed(name,title),m_basesim(ref),m_simul(0) {};
  TFCSSimulationRun( TFCSParametrizationBase* ref ) : TNamed( *ref ), m_basesim( ref ), m_simul( 0 ){};
  TFCSSimulationRun(TFCSParametrizationBase* ref, std::vector<TFCSSimulationState>& refsimul):TNamed(*ref),m_basesim(ref),m_simul(refsimul) {};

  TFCSParametrizationBase*          basesim() { return m_basesim; };
  std::vector<TFCSSimulationState>& simul() { return m_simul; };

private:
  TFCSParametrizationBase*         m_basesim;
  std::vector<TFCSSimulationState> m_simul;

  ClassDef( TFCSSimulationRun, 1 );
};

#if defined( __MAKECINT__ )
#  pragma link C++ class TFCSSimulationRun + ;
#endif

#endif
