/*
  Copyright (C) 2002-2018 CERN for the benefit of the ATLAS collaboration
 */

#include "CLHEP/Random/RandFlat.h"

namespace CLHEP {

/**

 * @brief Generates a random number using the provided HepRandomEngine.
 * 
 * @param engine Pointer to the HepRandomEngine instance used for generating the random number.
 * @return A random double value generated by the engine.
 */
// The above comment was written by an LLM. 
double RandFlat::shoot(HepRandomEngine *engine)
{
  return engine->random();
}

/**

 * @brief Generates a random double precision floating point number within a flat distribution.
 * 
 * @param engine Pointer to the HepRandomEngine object used to generate the random number.
 * @param a Lower bound of the range (inclusive).
 * @param b Upper bound of the range (inclusive).
 * @return A random double precision floating point number between a and b.
 */
// The above comment was written by an LLM. 
double RandFlat::shoot(HepRandomEngine *engine, double a, double b)
{
  return (b - a) * engine->random() + a;
}

/**

 * @brief Generates a random number from a flat distribution within a specified range.
 * 
 * @param engine Pointer to the HepRandomEngine instance used for generating the random number.
 * @param width The range of the flat distribution.
 * 
 * @return A random double value between 0 and the specified width.
 */
// The above comment was written by an LLM. 
double RandFlat::shoot(HepRandomEngine *engine, double width)
{
  return width * engine->random();
}

} // namespace CLHEP
