/*
  Copyright (C) 2002-2018 CERN for the benefit of the ATLAS collaboration
 */

#include "CLHEP/Random/RandFlat.h"

namespace CLHEP {

/**
 * Generates a random number using the provided HepRandomEngine instance.
 *
 * @param engine Pointer to the HepRandomEngine instance to use for generating the random number.
 * @return A randomly generated number.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
double RandFlat::shoot(HepRandomEngine *engine)
{
  return engine->random();
}

/**
 * Generates a random double precision floating point number within a specified range.
 *
 * @param engine Pointer to the HepRandomEngine instance used for generating random numbers.
 * @param a Lower bound of the range (inclusive).
 * @param b Upper bound of the range (inclusive).
 * @return A random double precision floating point number between a and b.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
double RandFlat::shoot(HepRandomEngine *engine, double a, double b)
{
  return (b - a) * engine->random() + a;
}

/**
 * Generates a random double value within a specified range
 * @param engine HepRandomEngine instance used for random number generation
 * @param width Range of the random values to be generated
 * @return A random double value between 0 and width
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
double RandFlat::shoot(HepRandomEngine *engine, double width)
{
  return width * engine->random();
}

} // namespace CLHEP
