/*
  Copyright (C) 2002-2018 CERN for the benefit of the ATLAS collaboration
 */

#include "CLHEP/Random/RandPoisson.h"

namespace CLHEP {

/**
 * Generates a random Poisson distributed variable using the provided HepRandomEngine.
 *
 * @param engine Pointer to the HepRandomEngine instance to use for random number generation.
 * @param mean Mean value of the Poisson distribution.
 * @return A randomly generated Poisson distributed double value.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
double RandPoisson::shoot(HepRandomEngine *engine, double mean)
{
  return engine->poisson(mean);
}

} // namespace CLHEP
