/*
  Copyright (C) 2002-2018 CERN for the benefit of the ATLAS collaboration
 */

#ifndef TRandomEngine_h
#define TRandomEngine_h 1

#include "CLHEP/Random/RandomEngine.h"

class TRandom3;

namespace CLHEP {

/**
 * Abstract base class for random number engines providing basic functionality
 * for generating random numbers and distributions
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
  class TRandomEngine : public HepRandomEngine {
  public:
    TRandomEngine();
    virtual ~TRandomEngine();

    virtual void setSeed( long seed, int dummy = 0 ) final;

    virtual double random() final;
    virtual double gauss( double mean, double stdDev ) final;
    virtual double poisson( double mean ) final;

  private:
    TRandom3* m_random;
  };

} // namespace CLHEP

#endif // TRandomEngine_h
