/*
  Copyright (C) 2002-2023 CERN for the benefit of the ATLAS collaboration
*/

struct counting_iterator {

  typedef size_t Index_t;

private:
  using self = counting_iterator;

public:
  using value_type = Index_t;
  using difference_type = typename std::make_signed<Index_t>::type;
  using pointer = Index_t *;
  using reference = Index_t &;
  using iterator_category = std::random_access_iterator_tag;

  counting_iterator() : value(0) {}
  explicit counting_iterator(value_type v) : value(v) {}

  value_type operator*() const { return value; }
  value_type operator[](difference_type n) const { return value + n; }

/**
 * Increment operator overload 
 * Increments the value and returns a reference to the current object 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  self &operator++() {
    ++value;
    return *this;
  }
/**
 * Prefixincrementoperator 
 * Returns the current object before incrementing the value
 * @return The current object with the previous value
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  self operator++(int) {
    self result{ value };
    ++value;
    return result;
  }
/**
 * Decrement operator overload 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  self &operator--() {
    --value;
    return *this;
  }
/**
 * DecrementOperator subtracts one from the current object value 
 * and returns the original value before decrementing * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  self operator--(int) {
    self result{ value };
    --value;
    return result;
  }
/**
 * AssignmentOperatorOverload 
 * Adds the specified difference to the current object
 * @param n The difference to add
 * @return A reference to the current object
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  self &operator+=(difference_type n) {
    value += n;
    return *this;
  }
/**
 * Assignment operator subtracting a difference type from the current object
 * @param n The difference type to be subtracted
 * @return A reference to the current object after subtraction
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  self &operator-=(difference_type n) {
    value -= n;
    return *this;
  }

  friend self operator+(self const &i, difference_type n) {
    return self(i.value + n);
  }
  friend self operator+(difference_type n, self const &i) {
    return self(i.value + n);
  }
  friend difference_type operator-(self const &x, self const &y) {
    return x.value - y.value;
  }
  friend self operator-(self const &i, difference_type n) {
    return self(i.value - n);
  }

  friend bool operator==(self const &x, self const &y) {
    return x.value == y.value;
  }
  friend bool operator!=(self const &x, self const &y) {
    return x.value != y.value;
  }
  friend bool operator<(self const &x, self const &y) {
    return x.value < y.value;
  }
  friend bool operator<=(self const &x, self const &y) {
    return x.value <= y.value;
  }
  friend bool operator>(self const &x, self const &y) {
    return x.value > y.value;
  }
  friend bool operator>=(self const &x, self const &y) {
    return x.value >= y.value;
  }

private:
  value_type value;
};
