/*
  Copyright (C) 2002-2021 CERN for the benefit of the ATLAS collaboration
*/

#ifndef GEOGPU_STRUCTS_H
#define GEOGPU_STRUCTS_H

#include "GeoRegion.h"

/**
 * Struct representing a sample index for random number generation
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
struct Rg_Sample_Index {
  int size;
  int index;
};

/**
 * Struct representing geometric data on the GPU
 * Contains information about cells and regions
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
struct GeoGpu {
  unsigned long ncells;
  CaloDetDescrElement *cells;
  unsigned int nregions;
  GeoRegion *regions;
  int max_sample;
  Rg_Sample_Index *sample_index;
};

#endif
