/*
  Copyright (C) 2002-2021 CERN for the benefit of the ATLAS collaboration
*/

#include "DEV_BigMem.h"
#include <vector>
#include <omp.h>

/**
 * Constructor for DEVBigMem class, initializes memory segment of specified size.
 *
 * @param s Size of the memory segment to be initialized.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
DEV_BigMem::DEV_BigMem( size_t s ) { // initialize to one seg with size s
  void* p;
  m_seg_size = s;
  p          = (void*)omp_target_alloc( m_seg_size, m_default_device );
  if ( p == NULL ) { std::cout << " ERROR: No space left on device for p in big mem." << std::endl; }
  m_ptrs.push_back( p );
  m_seg = 0;
  m_used.push_back( 0 );
};

DEV_BigMem::~DEV_BigMem() {
  for ( int i = 0; i < m_ptrs.size(); i++ ) omp_target_free( m_ptrs[i], m_default_device );
};

/**
 * Allocates memory segment on default device and updates internal state.
 *
 * Allocates a new memory segment of size m_seg_size on the default device,
 * stores the pointer in the list of pointers, increments the segment counter,
 * and initializes the corresponding used flag to zero.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
void DEV_BigMem::add_seg() {
  void* p;
  p = (void*)omp_target_alloc( m_seg_size, m_default_device );
  if ( p == NULL ) { std::cout << " ERROR: No space left on device for p in big mem." << std::endl; }
  m_ptrs.push_back( p );
  m_seg++;
  m_used.push_back( 0 );
};
