/*
  Copyright (C) 2002-2023 CERN for the benefit of the ATLAS collaboration
*/

#include "DEV_BigMem.h"
#include <vector>
#include <Kokkos_Core.hpp>

/**
 * Constructor for DEVBigMem class, initializes memory segment of specified size.
 *
 * @param s The size of the initial memory segment.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
DEV_BigMem::DEV_BigMem(size_t s) { // initialize to one seg with size s
  m_seg_size = s;

  void *p{ nullptr };
  try {
    p = Kokkos::kokkos_malloc("bigmem buffer", m_seg_size);
  }
  catch (...) {
    std::cerr << "unable to allocate " << m_seg_size
              << " bytes for bigmem buffer\n";
    return;
  }
  m_ptrs.push_back(p);
  m_seg = 0;
  m_used.push_back(0);
}

/**
 * Destructor to release allocated memory resources.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
DEV_BigMem::~DEV_BigMem() {
  for (long unsigned int i = 0; i < m_ptrs.size(); i++) {
    Kokkos::kokkos_free(m_ptrs[i]);
  }
}

/**
 * Allocates a new segment of memory on the device and adds it to the list of pointers.
 *
 * Attempts to allocate a block of memory of size m_seg_size bytes using Kokkos.
 * If allocation fails an error message is printed and the function returns without modifying the state.
 * On success the newly allocated pointer is added to the list of pointers and the segment counter is incremented.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
void DEV_BigMem::add_seg() {

  void *p{ nullptr };
  try {
    p = Kokkos::kokkos_malloc("bigmem buffer", m_seg_size);
  }
  catch (...) {
    std::cerr << "unable to allocate " << m_seg_size
              << " bytes for bigmem buffer\n";
    return;
  }
  // std::cout << "DEV_BM add_seg() " << m_seg << " " << p << std::endl;
  m_ptrs.push_back(p);
  m_seg++;
  m_used.push_back(0);
};
