/*
  Copyright (C) 2002-2021 CERN for the benefit of the ATLAS collaboration
*/

#include "gpuQ.h"
#include "DEV_BigMem.h"
#include <vector>

/**
 * Constructor for DEVBigMem class initializing memory segment of specified size
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
DEV_BigMem::DEV_BigMem(size_t s) { // initialize to one seg with size s
  void *p;
  m_seg_size = s;
  gpuQ(hipMalloc(&p, m_seg_size));
  m_ptrs.push_back(p);
  m_seg = 0;
  m_used.push_back(0);
};

/**
 * Destructor for DEVBigMem class 
 * Releases memory allocated on the GPU for each pointer in mPtrs vector
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
DEV_BigMem::~DEV_BigMem() {
  for (int i = 0; i < m_ptrs.size(); i++)
    gpuQ(hipFree(m_ptrs[i]));
};

/**
 * Allocates memory segment on the device and updates internal state.
 *
 * @brief Adds a new memory segment to the device.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
void DEV_BigMem::add_seg() {
  void *p;
  gpuQ(hipMalloc((void **)&p, m_seg_size));
  m_ptrs.push_back(p);
  m_seg++;
  m_used.push_back(0);
};
