/*
  Copyright (C) 2002-2022 CERN for the benefit of the ATLAS collaboration
*/

#include "GeoLoadGpu.h"
#include "AlpakaDefs.h"
#include <alpaka/alpaka.hpp>
#include <iostream>

/**
 * Constructor for the GeoLoadGpuImpl class, initializes member variables with allocated host and accelerator buffers.
   * Member variable storing buffer of type RgSampleIndex on the host.
  * Member variable storing buffer of type GeoRegion on the host.
  * Member variable storing buffer of type GeoGpu on the host.
  * Member variable storing vector of buffers of type LongLong on the host.
  * Member variable storing buffer of type CaloDetDescrElement on the accelerator.
  * Member variable storing buffer of type RgSampleIndex on the accelerator.
  * Member variable storing buffer of type GeoRegion on the accelerator.
  * Member variable storing buffer of type GeoGpu on the accelerator.
  * Member variable storing vector of buffers of type LongLong on the accelerator.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
class GeoLoadGpu::Impl {
public:
/**
 * Default constructor initializing member variables with allocated buffers.
 */
// The above comment was written by an LLM. 
  Impl()
    : sample_index_buf_host{alpaka::allocBuf<Rg_Sample_Index, Idx>(alpaka::getDevByIdx<Host>(0u), Idx{1})}
    , regions_buf_host{alpaka::allocBuf<GeoRegion, Idx>(alpaka::getDevByIdx<Host>(0u), Idx{1})}
    , geogpu_buf_host{alpaka::allocBuf<GeoGpu, Idx>(alpaka::getDevByIdx<Host>(0u), Idx{1})}
    , cells_buf_acc{alpaka::allocBuf<CaloDetDescrElement, Idx>(alpaka::getDevByIdx<Acc>(0u), Idx{1})}
    , sample_index_buf_acc{alpaka::allocBuf<Rg_Sample_Index, Idx>(alpaka::getDevByIdx<Acc>(0u), Idx{1})}
    , regions_buf_acc{alpaka::allocBuf<GeoRegion, Idx>(alpaka::getDevByIdx<Acc>(0u), Idx{1})}
    , geogpu_buf_acc{alpaka::allocBuf<GeoGpu, Idx>(alpaka::getDevByIdx<Acc>(0u), Idx{1})}
  {
  }

  BufHostSampleIndex sample_index_buf_host;
  BufHostGeoRegion regions_buf_host;
  BufHostGeoGpu geogpu_buf_host;
  std::vector<BufHostLongLong> reg_vec_host;

  BufAccCaloDDE cells_buf_acc;
  BufAccSampleIndex sample_index_buf_acc;
  BufAccGeoRegion regions_buf_acc;
  BufAccGeoGpu geogpu_buf_acc;
  std::vector<BufAccLongLong> reg_vec_acc;
};

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/* Test Kernels */
struct TestHelloKernel
{
  template<typename TAcc>
/**
 * @brief Performs operation on GPU thread
 * @param acc Accelerator object
 * @return None
 */
// The above comment was written by an LLM. 
  ALPAKA_FN_ACC auto operator()(TAcc const& acc) const -> void
  {
    auto const idx = alpaka::getIdx<alpaka::Grid, alpaka::Threads>(acc)[0];
    printf( "Hello, I am from GPU thread %d\n", static_cast<unsigned>(idx) );
  }
};

/**
 * @brief Executes the test cell kernel operation
 * @param acc accelerator object
 * @param cells array of calibration detector description elements
 * @param index index of the element to operate on
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
struct TestCellKernel
{
  template<typename TAcc>
/**
 * @brief Performs operation on calibration detector description element
 * @param acc accelerator object
 * @param cells array of calibration detector description elements
 * @param index index of the element to operate on
 */
// The above comment was written by an LLM. 
  ALPAKA_FN_ACC auto operator()(TAcc const& /*acc*/
				, const CaloDetDescrElement* cells
				, unsigned long index) const -> void
  {
    const CaloDetDescrElement* cell   = &cells[index];
    int                  sample = cell->getSampling();
    float                eta    = cell->eta();
    float                phi    = cell->phi();

    long long hashid = cell->calo_hash();

    printf( "From GPU cell index %ld , hashid=%lld, eta=%f, phi=%f, sample=%d \n"
	    , index
	    , hashid
	    , eta
	    , phi
	    , sample );
  }
};

/**
 * Brief description: Applies an operation to a set of calorimeter detector elements.
 *
 * Detailed description: This function takes in various parameters including 
 * a TAcc object, an array of CaloDetDescrElement objects, an array of GeoRegion objects,
 * and several integer indices. It uses these inputs to access specific 
 * calorimeter detector elements and print out their properties.
 *
 * Parameters:
 *   acc - The TAcc object used in the operation.
 *   cells - An array of CaloDetDescrElement objects representing the calorimeter detector elements.
 *   regions - An array of GeoRegion objects defining the geometric regions of interest.
 *   nregions - The number of regions.
 *   ncells - The number of cells.
 *   r - The index of the current region.
 *   ir - The row index within the current region's cell grid.
 *   ip - The column index within the current region's cell grid.
 *
 * Returns: None
  
 * Brief description: Fills energy histograms with data from a simulation run.
 *
 * Detailed description: This function takes in parameters such as TH1 pointers, 
 * a TFCSShapeValidation pointer, an integer, and a TFCSSimulationRun reference. 
 * It fills energy histograms based on the input data.
 *
 * Parameters:
 *   histos - Pointers to TH1 objects representing the energy histograms.
 *   validation - A TFCSShapeValidation pointer used in the filling process.
 *   type - An integer indicating the type of filling to perform.
 *   run - A TFCSSimulationRun reference providing the simulation data.
 *
 * Returns: None
 
 * Brief description: Compares the shapes of two simulation runs.
 *
 * Detailed description: This function takes in parameters such as a TFCSShapeValidation pointer, 
 * integers, TFCSSimulationRun references, and a TString. It compares the shapes 
 * of the two simulation runs based on the input data.
 *
 * Parameters:
 *   validation - A TFCSShapeValidation pointer used in the comparison.
 *   type - An integer indicating the type of comparison to perform.
 *   run1 - A TFCSSimulationRun reference providing the first simulation data.
 *   run2 - A TFCSSimulationRun reference providing the second simulation data.
 *   label - A TString used to label the comparison results.
 *
 * Returns: None
 
 * Brief description: Draws a 2D histogram.
 *
 * Detailed description: This function takes in parameters such as a TH1 pointer, 
 * doubles, a boolean, and TStrings. It draws a 2D histogram based on the input data.
 *
 * Parameters:
 *   histo - A TH1 pointer representing the histogram to draw.
 *   xMin - A double specifying the minimum x-value.
 *   xMax - A double specifying the maximum x-value.
 *   normalize - A boolean indicating whether to normalize the histogram.
 *   titleX - A TString used as the x-axis title.
 *   titleY - A TString used as the y-axis title.
 *
 * Returns: None
 
 * Brief description: Runs the TFCSShapeValidation algorithm.
 *
 * Detailed description: This function takes in parameters such as integers, 
 * a double, an integer, a TString, a long, and integers. It runs the TFCSShapeValidation 
 * algorithm based on the input data.
 *
 * Parameters:
 *   type - An integer indicating the type of validation to perform.
 *   nevents - An integer specifying the number of events.
 *   energy - A double specifying the energy threshold.
 *   npart - An integer specifying the number of particles.
 *   filename - A TString specifying the input file name.
 *   seed - A long specifying the random seed.
 *   pdg - An integer specifying the particle PDG code.
 *   charge - An integer specifying the particle charge.
 *   mother - An integer specifying the mother particle PDG code.
 *
 * Returns: None
 
 * Brief description: Bins logarithmically.
 *
 * Detailed description: This function takes in a TAxis pointer as input and 
 * performs a logarithmic binning operation.
 *
 * Parameters:
 *   axis - A TAxis pointer representing the axis to bin.
 *
 * Returns: None
 
 * Brief description: Inserts an element into a vector.
 *
 * Detailed description: This function takes in a vector iterator and an element 
 * as input and inserts the element at the specified position.
 *
 * Parameters:
 *   iter - A vector iterator specifying the insertion point.
 *   element - The element to be inserted.
 *
 * Returns: None
 
 * Brief description: Throws an exception if a value is not of the expected kind.
 *
 * Detailed description: This function checks if a value is of the expected kind and 
 * throws an exception if it is not.
 *
 * Parameters:
 *   kind - The expected kind of the value.
 *
 * Returns: None
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
struct TestGeoKernel
{
  template<typename TAcc>
/**
 * Brief description: Applies an operation to a set of calorimeter detector elements.
 *
 * Detailed description: This function takes in various parameters including 
 * a TAcc object, an array of CaloDetDescrElement objects, an array of GeoRegion objects,
 * and several integer indices. It uses these inputs to access specific 
 * calorimeter detector elements and print out their properties.
 *
 * Parameters:
 *   acc - The TAcc object used in the operation.
 *   cells - An array of CaloDetDescrElement objects representing the calorimeter detector elements.
 *   regions - An array of GeoRegion objects defining the geometric regions of interest.
 *   nregions - The number of regions (not used in this implementation).
 *   ncells - The number of cells (not used in this implementation).
 *   r - The index of the current region.
 *   ir - The row index within the current region's cell grid.
 *   ip - The column index within the current region's cell grid.
 *
 * Returns: None
 */
// The above comment was written by an LLM. 
  ALPAKA_FN_ACC auto operator()(TAcc const& /*acc*/
				, const CaloDetDescrElement* cells
				, const GeoRegion* regions
				, unsigned int /*nregions*/
				, unsigned long /*ncells*/
				, int r, int ir, int ip) const -> void
  {
    int                neta  = regions[r].cell_grid_eta();
    int                nphi  = regions[r].cell_grid_phi();
    unsigned long long index = regions[r].cell_grid_g()[ir * nphi + ip];
    printf( " From GPU.., region %d, cell_grid[%d][%d]: [%d][%d] index=%llu \n"
	    , r
	    , ir
	    , ip
	    , neta
	    , nphi
	    , index );

  const CaloDetDescrElement* c = &cells[index];

  long long hashid = c->calo_hash();
  long long id     = c->identify();
  int       sample = c->getSampling();
  float     eta    = c->eta();
  float     phi    = c->phi();

  printf( " From GPU.., region %d, cell_grid[%d][%d]: index %llu index, hashid=%lld,eta=%f, phi=%f, sample=%d , ID=%lld "
          "cell_ptr=%p \n"
	  , r
	  , ir
	  , ip
	  , index
	  , hashid
	  , eta
	  , phi
	  , sample
	  , id
	  , regions[r].all_cells() );
  
  CaloDetDescrElement cc = ( regions[r].all_cells() )[index];
  printf( " GPU test region have cells: cell index %llu, eta=%f phi=%f size of cell*GPU=%lu\n"
	  , index
	  , cc.eta()
	  , cc.phi()
	  , sizeof( CaloDetDescrElement* ) );
  }
};

/**
 * Applies an operation to a given accumulator and geometry object.
 *
 * This function performs calculations based on the input accumulator, 
 * geometry object, and integer parameters, accessing geometry properties 
 * and calculating indices to retrieve cell elements.
 *
 * Parameters:
 *   acc - The accumulator object.
 *   geo - A pointer to the geometry object.
 *   r - An integer parameter.
 *   ir - An integer parameter.
 *   ip - An integer parameter.
 *
 * Returns: None
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
struct TestGeoKernel_G
{
  template<typename TAcc>
/**
 * Brief description: Applies an operation to a given accumulator and geometry object.
 *
 * Detailed description: This function takes in an accumulator, a geometry object,
 * and integer parameters, and performs an operation based on these inputs.
 * It accesses various properties of the geometry object, such as its regions and cells,
 * and uses them to calculate indices and retrieve specific cell elements.
 * The results of these calculations are then printed to the console.
 *
 * Parameters:
 *   acc - The accumulator object.
 *   geo - A pointer to the geometry object.
 *   r - An integer parameter.
 *   ir - An integer parameter.
 *   ip - An integer parameter.
 *
 * Returns: None
 */
// The above comment was written by an LLM. 
  ALPAKA_FN_ACC auto operator()(TAcc const& /*acc*/
				, const GeoGpu* geo
				, int r, int ir, int ip) const -> void
  {
    const GeoRegion*           regions = ( *geo ).regions;
    const CaloDetDescrElement* cells   = geo->cells;

    int                neta  = regions[r].cell_grid_eta();
    int                nphi  = regions[r].cell_grid_phi();
    unsigned long long index = regions[r].cell_grid_g()[ir * nphi + ip];
    printf( " From GPU.., region %d, cell_grid[%d][%d]: [%d][%d] index=%lld \n"
	    , r
	    , ir
	    , ip
	    , neta
	    , nphi
	    , index );

  const CaloDetDescrElement* c = &cells[index];

  long long hashid = c->calo_hash();
  long long id     = c->identify();
  int       sample = c->getSampling();
  float     eta    = c->eta();
  float     phi    = c->phi();

  printf( " From GPU.., region %d, cell_grid[%d][%d]: index %llu index, hashid=%lld,eta=%f, phi=%f, sample=%d , ID=%lld "
          "cell_ptr=%p \n"	  
	  , r
	  , ir
	  , ip
	  , index
	  , hashid
	  , eta
	  , phi
	  , sample
	  , id
	  , regions[r].all_cells() );

  CaloDetDescrElement cc = ( regions[r].all_cells() )[index];
  printf( " GPU test region have cells: cell index %llu, eta=%f phi=%f size of cell*GPU=%lu\n"
	  , index
	  , cc.eta()
	  , cc.phi()
	  , sizeof( CaloDetDescrElement* ) );
  }
};

/* Test Utilities */
bool GeoLoadGpu::TestGeo() {
  QueueAcc queue(alpaka::getDevByIdx<Acc>(Idx{0}));

  WorkDiv workdiv(Idx{1},Idx{1},Idx{1});
  TestGeoKernel testGeo;
  alpaka::exec<Acc>(queue
		    , workdiv
		    , testGeo
		    , m_cells_d
		    , m_regions_d
		    , m_ncells
		    , m_nregions
		    , 14, 0, 32);
  TestGeoKernel_G testGeo_G;
  alpaka::exec<Acc>(queue
		    , workdiv
		    , testGeo_G
		    , get_geoPtr()
		    , 14, 0, 32);
  alpaka::wait(queue);

  std::cout << "TesGeo finished " << std::endl;

  long long* c   = m_regions[14].cell_grid();
  int        np  = m_regions[14].cell_grid_phi();
  int        ne  = m_regions[14].cell_grid_eta();
  int        idx = c[0 * np + 32];
  Identifier Id  = m_cellid_array[idx];
  std::cout << "From Host: Region[14]Grid[0][32]: index=" << idx << ", ID=" << Id
            << ", HashCPU=" << ( *m_cells )[Id]->calo_hash() << ", neta=" << ne << ",  nphi=" << np
            << ", eta=" << ( *m_cells )[Id]->eta() << std::endl;

  return true;
  // end test
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
bool GeoLoadGpu::SanityCheck() {
  // sanity check/test
  QueueAcc queue(alpaka::getDevByIdx<Acc>(Idx{0}));

  WorkDiv workdiv(Idx{1},Idx{1},Idx{1});
  TestHelloKernel testHello;
  alpaka::exec<Acc>(queue
		    , workdiv
		    , testHello);
  TestCellKernel testCell;
  alpaka::exec<Acc>(queue
		    , workdiv
		    , testCell
		    , m_cells_d
		    , 1872);
  alpaka::wait(queue);

  std::cout << " ID of 2000's cell " << m_cellid_array[2000] << std::endl;
  Identifier Id = m_cellid_array[2000];
  std::cout << "ID of cell 2000: " << ( *m_cells )[Id]->identify() << "hashid: " << ( *m_cells )[Id]->calo_hash()
            << std::endl;
  std::cout << "Size of Identify: " << sizeof( Identifier ) << "size of Region: " << sizeof( GeoRegion ) << std::endl;

  std::cout << "GPU Kernel cell test lauched" << std::endl;

  return true;
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
GeoGpu *GeoLoadGpu::Geo_g;
unsigned long GeoLoadGpu::num_cells;

/**
 * Returns a pointer to the sample index buffer on the host device.
 *
 * @return Pointer to the sample index buffer
 */
// The above comment was written by an LLM. 
Rg_Sample_Index* GeoLoadGpu::get_sample_index_h_al()
{
  if(!pImpl) pImpl = new Impl();

  pImpl->sample_index_buf_host = alpaka::allocBuf<Rg_Sample_Index, Idx>(alpaka::getDevByIdx<Host>(0u), static_cast<Idx>(m_max_sample));
  return (Rg_Sample_Index*)alpaka::getPtrNative(pImpl->sample_index_buf_host);
}

/**
 * Returns a pointer to an array of geographic regions allocated on the GPU
 * 
 * @return Pointer to an array of GeoRegion objects
 */
// The above comment was written by an LLM. 
GeoRegion* GeoLoadGpu::get_regions_al()
{
  if(!pImpl) pImpl = new Impl();

  pImpl->regions_buf_host = alpaka::allocBuf<GeoRegion, Idx>(alpaka::getDevByIdx<Host>(0u), Idx{m_nregions});
  return (GeoRegion*)alpaka::getPtrNative(pImpl->regions_buf_host);
}

/**
 * @brief Retrieves the cell grid allocated on the GPU
 * @param neta number of eta bins
 * @param nphi number of phi bins
 * @return pointer to the cell grid on the GPU
 */
// The above comment was written by an LLM. 
long long* GeoLoadGpu::get_cell_grid_al(int neta, int nphi)
{
  if(!pImpl) pImpl = new Impl();

  BufHostLongLong cells = alpaka::allocBuf<long long, Idx>(alpaka::getDevByIdx<Host>(0u), static_cast<Idx>(neta*nphi));
  pImpl->reg_vec_host.push_back(cells);
  return (long long*)alpaka::getPtrNative(cells);
}

/**
 * @brief Loads geometry onto the GPU using Alpaka.
 *
 * This function checks if the geometry is empty and returns false if it is.
 * It then initializes the Alpaka device and allocates memory for the cells,
 * regions, and sample indices on the GPU. The function also copies the
 * cell and region data from the host to the GPU and sets up the pointers
 * for the GPU data structures.
 *
 * @return True if the loading is successful, false otherwise.
 */
// The above comment was written by an LLM. 
bool GeoLoadGpu::LoadGpu_al() {
  if ( !m_cells || m_ncells == 0 ) {
    std::cout << "Geometry is empty " << std::endl;
    return false;
  }

  if(!pImpl) pImpl = new Impl();

  auto dev = alpaka::getDevByIdx<Acc>(Idx{0});
  std::cout << "Executing on GPU: " << alpaka::getName(dev) << std::endl;

  QueueAcc queue(dev);
  
  BufHostGeoGpu geo_gpu_host = alpaka::allocBuf<GeoGpu,Idx>(alpaka::getDevByIdx<Host>(0u),Idx{1});
  GeoGpu* geo_gpu_ptr = alpaka::getPtrNative(geo_gpu_host);
  num_cells = m_ncells;

  // Allocate Device memory for cells and copy cells as array
  // move cells on host to a array first
  pImpl->cells_buf_acc = alpaka::allocBuf<CaloDetDescrElement, Idx>(alpaka::getDevByIdx<Acc>(0u), m_ncells);
  m_cells_d = alpaka::getPtrNative(pImpl->cells_buf_acc);

  std::cout << "device Malloc " << m_ncells << " cells" << std::endl;

  BufHostCaloDDE cells_buf_host = alpaka::allocBuf<CaloDetDescrElement, Idx>(alpaka::getDevByIdx<Host>(0u),m_ncells);
  CaloDetDescrElement* cells_Host = alpaka::getPtrNative(cells_buf_host);

  m_cellid_array                  = (Identifier*)malloc(m_ncells*sizeof(Identifier));

  // create an array of cell identities, they are in order of hashids.
  int ii = 0;
  for(t_cellmap::iterator ic = m_cells->begin(); ic != m_cells->end(); ++ic) {
    cells_Host[ii]     = *( *ic ).second;
    Identifier id      = ( ( *ic ).second )->identify();
    m_cellid_array[ii] = id;
    ii++;
  }

  alpaka::memcpy(queue,pImpl->cells_buf_acc,cells_buf_host);
  alpaka::wait(queue);
  
  std::cout << "device Memcpy " << ii << "/" << m_ncells << " cells"
            << " Total:" << ii * sizeof( CaloDetDescrElement ) << " Bytes" << std::endl;

  if ( 0 ) {
    if ( !SanityCheck() ) { return false; }
  }

  pImpl->sample_index_buf_acc = alpaka::allocBuf<Rg_Sample_Index, Idx>(alpaka::getDevByIdx<Acc>(0u), static_cast<Idx>(m_max_sample));
  Rg_Sample_Index* SampleIndex_g = alpaka::getPtrNative(pImpl->sample_index_buf_acc);

  // copy sample_index array  to gpu
  alpaka::memcpy(queue,pImpl->sample_index_buf_acc,pImpl->sample_index_buf_host);
  alpaka::wait(queue);

  // each Region allocate a grid (long Long) gpu array
  //  copy array to GPU
  //  save to regions m_cell_g ;
  for(unsigned int ir = 0; ir < m_nregions; ++ir) {
    BufAccLongLong gv = alpaka::allocBuf<long long, Idx>(alpaka::getDevByIdx<Acc>(0u), static_cast<Idx>(m_regions[ir].cell_grid_eta()* m_regions[ir].cell_grid_phi()));
    pImpl->reg_vec_acc.push_back(gv);
    long long* ptr_g = alpaka::getPtrNative(gv);

    alpaka::memcpy(queue,gv,pImpl->reg_vec_host[ir]);
    alpaka::wait(queue);

    m_regions[ir].set_cell_grid_g( ptr_g );
    m_regions[ir].set_all_cells( m_cells_d ); // set this so all region instance know where the GPU cells are, before copy to GPU
  }

  // GPU allocate Regions data  and load them to GPU as array of regions

  pImpl->regions_buf_acc = alpaka::allocBuf<GeoRegion,Idx>(alpaka::getDevByIdx<Acc>(0u), Idx{m_nregions});
  m_regions_d = alpaka::getPtrNative(pImpl->regions_buf_acc);

  alpaka::memcpy(queue,pImpl->regions_buf_acc,pImpl->regions_buf_host);

  geo_gpu_ptr->cells        = m_cells_d;
  geo_gpu_ptr->ncells       = m_ncells;
  geo_gpu_ptr->nregions     = m_nregions;
  geo_gpu_ptr->regions      = m_regions_d;
  geo_gpu_ptr->max_sample   = m_max_sample;
  geo_gpu_ptr->sample_index = SampleIndex_g;


  std::cout << "alpaka GEO\n";
  std::cout << "ncells: " << geo_gpu_ptr->ncells << "\n";
  std::cout << "regions: " << m_nregions << "\n";
  std::cout << "=================================\n";
  
  // Now copy this to GPU and set the static member to this pointer
  pImpl->geogpu_buf_acc = alpaka::allocBuf<GeoGpu,Idx>(alpaka::getDevByIdx<Acc>(0u), Idx{sizeof(GeoGpu)});
  GeoGpu* Gptr = alpaka::getPtrNative(pImpl->geogpu_buf_acc);

  alpaka::memcpy(queue,pImpl->geogpu_buf_acc,geo_gpu_host);
  alpaka::wait(queue);
  
  m_geo_d = Gptr;
  Geo_g = Gptr;

  // more test for region grids
  if ( 0 ) { return TestGeo(); }
  return true;
}

