/*
  Copyright (C) 2002-2022 CERN for the benefit of the ATLAS collaboration
*/

#include "GeoLoadGpu.h"
#include "AlpakaDefs.h"
#include <alpaka/alpaka.hpp>
#include <iostream>

/**
 * Default constructor for GeoLoadGpuImpl class 
   * Member variable to store sample index buffer on host device 
  * Member variable to store geometric region buffer on host device 
  * Member variable to store geometric gpu buffer on host device 
  * Member variable to store vector of long long integer buffers on host device 
  * Member variable to store calo detector element buffer on accelerator device 
  * Member variable to store sample index buffer on accelerator device 
  * Member variable to store geometric region buffer on accelerator device 
  * Member variable to store geometric gpu buffer on accelerator device 
  * Member variable to store vector of long long integer buffers on accelerator device 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
class GeoLoadGpu::Impl {
public:
/**
 * Constructor initializing buffers for host and accelerator devices
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
  Impl()
    : sample_index_buf_host{alpaka::allocBuf<Rg_Sample_Index, Idx>(alpaka::getDevByIdx<Host>(0u), Idx{1})}
    , regions_buf_host{alpaka::allocBuf<GeoRegion, Idx>(alpaka::getDevByIdx<Host>(0u), Idx{1})}
    , geogpu_buf_host{alpaka::allocBuf<GeoGpu, Idx>(alpaka::getDevByIdx<Host>(0u), Idx{1})}
    , cells_buf_acc{alpaka::allocBuf<CaloDetDescrElement, Idx>(alpaka::getDevByIdx<Acc>(0u), Idx{1})}
    , sample_index_buf_acc{alpaka::allocBuf<Rg_Sample_Index, Idx>(alpaka::getDevByIdx<Acc>(0u), Idx{1})}
    , regions_buf_acc{alpaka::allocBuf<GeoRegion, Idx>(alpaka::getDevByIdx<Acc>(0u), Idx{1})}
    , geogpu_buf_acc{alpaka::allocBuf<GeoGpu, Idx>(alpaka::getDevByIdx<Acc>(0u), Idx{1})}
  {
  }

  BufHostSampleIndex sample_index_buf_host;
  BufHostGeoRegion regions_buf_host;
  BufHostGeoGpu geogpu_buf_host;
  std::vector<BufHostLongLong> reg_vec_host;

  BufAccCaloDDE cells_buf_acc;
  BufAccSampleIndex sample_index_buf_acc;
  BufAccGeoRegion regions_buf_acc;
  BufAccGeoGpu geogpu_buf_acc;
  std::vector<BufAccLongLong> reg_vec_acc;
};

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/* Test Kernels */
struct TestHelloKernel
{
  template<typename TAcc>
/**
 * @brief Performs operation on GPU thread
 * @param acc Accelerator object
 * @return None
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
  ALPAKA_FN_ACC auto operator()(TAcc const& acc) const -> void
  {
    auto const idx = alpaka::getIdx<alpaka::Grid, alpaka::Threads>(acc)[0];
    printf( "Hello, I am from GPU thread %d\n", static_cast<unsigned>(idx) );
  }
};

/**
 * Brief description: Executes the test cell kernel operation.
 *
 * Detailed description: This function is responsible for printing cell details from the GPU.
 *
 * Parameters: 
 * accelerator object 
 * calorimeter detector descriptor elements array 
 * cell index 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
struct TestCellKernel
{
  template<typename TAcc>
/**
 * Brief description: Prints cell details from GPU.
 *
 * Detailed description: This function takes an accelerator object, 
 * an array of calorimeter detector descriptor elements, and an index,
 * and prints the corresponding cell's hash id, eta, phi, and sampling value.
 *
 * Parameters:
 * acc - Accelerator object
 * cells - Array of calorimeter detector descriptor elements
 * index - Index of the cell to print details for
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
  ALPAKA_FN_ACC auto operator()(TAcc const& /*acc*/
				, const CaloDetDescrElement* cells
				, unsigned long index) const -> void
  {
    const CaloDetDescrElement* cell   = &cells[index];
    int                  sample = cell->getSampling();
    float                eta    = cell->eta();
    float                phi    = cell->phi();

    long long hashid = cell->calo_hash();

    printf( "From GPU cell index %ld , hashid=%lld, eta=%f, phi=%f, sample=%d \n"
	    , index
	    , hashid
	    , eta
	    , phi
	    , sample );
  }
};

/**
 * Brief description: Operator function to access and print cell grid information from GPU.
 *
 * Detailed description: This function takes in various parameters and prints out detailed information about the cell grid.
 *
 * Parameters:
 * @param acc acceleration structure
 * @param cells array of detector descriptor elements
 * @param regions array of geographic regions
 * @param nregions number of regions
 * @param ncells number of cells
 * @param r region index
 * @param ir row index within the region
 * @param ip column index within the region
 *
 * Returns: None
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
struct TestGeoKernel
{
  template<typename TAcc>
/**
 * Brief description: Operator function to access and print cell grid information from GPU.
 *
 * Detailed description: This function takes in various parameters such as 
 * acceleration structure, detector descriptor elements, geographic regions, 
 * and indices, and prints out detailed information about the cell grid, including 
 * region number, cell grid coordinates, index values, hash IDs, eta and phi values, 
 * sampling rates, and identification numbers. It also tests the retrieval of 
 * cell data from the GPU and prints out the corresponding cell's properties.
 *
 * Parameters:
 * @param acc acceleration structure
 * @param cells array of detector descriptor elements
 * @param regions array of geographic regions
 * @param nregions number of regions
 * @param ncells number of cells
 * @param r region index
 * @param ir row index within the region
 * @param ip column index within the region
 *
 * Returns: None
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
  ALPAKA_FN_ACC auto operator()(TAcc const& /*acc*/
				, const CaloDetDescrElement* cells
				, const GeoRegion* regions
				, unsigned int /*nregions*/
				, unsigned long /*ncells*/
				, int r, int ir, int ip) const -> void
  {
    int                neta  = regions[r].cell_grid_eta();
    int                nphi  = regions[r].cell_grid_phi();
    unsigned long long index = regions[r].cell_grid_g()[ir * nphi + ip];
    printf( " From GPU.., region %d, cell_grid[%d][%d]: [%d][%d] index=%llu \n"
	    , r
	    , ir
	    , ip
	    , neta
	    , nphi
	    , index );

  const CaloDetDescrElement* c = &cells[index];

  long long hashid = c->calo_hash();
  long long id     = c->identify();
  int       sample = c->getSampling();
  float     eta    = c->eta();
  float     phi    = c->phi();

  printf( " From GPU.., region %d, cell_grid[%d][%d]: index %llu index, hashid=%lld,eta=%f, phi=%f, sample=%d , ID=%lld "
          "cell_ptr=%p \n"
	  , r
	  , ir
	  , ip
	  , index
	  , hashid
	  , eta
	  , phi
	  , sample
	  , id
	  , regions[r].all_cells() );
  
  CaloDetDescrElement cc = ( regions[r].all_cells() )[index];
  printf( " GPU test region have cells: cell index %llu, eta=%f phi=%f size of cell*GPU=%lu\n"
	  , index
	  , cc.eta()
	  , cc.phi()
	  , sizeof( CaloDetDescrElement* ) );
  }
};

/**
 * Applies an accumulator to a geometric object on a GPU.
 *
 * This function operates on a geometric object, applying an accumulator 
 * to a specified cell within the object, utilizing region indices and 
 * cell coordinates.
 *
 * Parameters:
 *   acc        - Accumulator to be applied
 *   geo        - Pointer to the geometric object
 *   r         - Region index
 *   ir        - Row index of the cell grid
 *   ip        - Column index of the cell grid
 *
 * Returns: None 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
struct TestGeoKernel_G
{
  template<typename TAcc>
/**
 * Brief description: Applies an accumulator to a geometric object on a GPU.
 *
 * Detailed description: This function takes in various parameters including 
 * a geometric object, region indices, and cell coordinates, and applies 
 * an accumulator to the specified cell within the geometric object.
 *
 * Parameters:
 *   acc        - The accumulator to apply
 *   geo        - A pointer to the geometric object
 *   r         - The region index
 *   ir        - The row index of the cell grid
 *   ip        - The column index of the cell grid
 *
 * Returns: None
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
  ALPAKA_FN_ACC auto operator()(TAcc const& /*acc*/
				, const GeoGpu* geo
				, int r, int ir, int ip) const -> void
  {
    const GeoRegion*           regions = ( *geo ).regions;
    const CaloDetDescrElement* cells   = geo->cells;

    int                neta  = regions[r].cell_grid_eta();
    int                nphi  = regions[r].cell_grid_phi();
    unsigned long long index = regions[r].cell_grid_g()[ir * nphi + ip];
    printf( " From GPU.., region %d, cell_grid[%d][%d]: [%d][%d] index=%lld \n"
	    , r
	    , ir
	    , ip
	    , neta
	    , nphi
	    , index );

  const CaloDetDescrElement* c = &cells[index];

  long long hashid = c->calo_hash();
  long long id     = c->identify();
  int       sample = c->getSampling();
  float     eta    = c->eta();
  float     phi    = c->phi();

  printf( " From GPU.., region %d, cell_grid[%d][%d]: index %llu index, hashid=%lld,eta=%f, phi=%f, sample=%d , ID=%lld "
          "cell_ptr=%p \n"	  
	  , r
	  , ir
	  , ip
	  , index
	  , hashid
	  , eta
	  , phi
	  , sample
	  , id
	  , regions[r].all_cells() );

  CaloDetDescrElement cc = ( regions[r].all_cells() )[index];
  printf( " GPU test region have cells: cell index %llu, eta=%f phi=%f size of cell*GPU=%lu\n"
	  , index
	  , cc.eta()
	  , cc.phi()
	  , sizeof( CaloDetDescrElement* ) );
  }
};

/* Test Utilities */
bool GeoLoadGpu::TestGeo() {
  QueueAcc queue(alpaka::getDevByIdx<Acc>(Idx{0}));

  WorkDiv workdiv(Idx{1},Idx{1},Idx{1});
  TestGeoKernel testGeo;
  alpaka::exec<Acc>(queue
		    , workdiv
		    , testGeo
		    , m_cells_d
		    , m_regions_d
		    , m_ncells
		    , m_nregions
		    , 14, 0, 32);
  TestGeoKernel_G testGeo_G;
  alpaka::exec<Acc>(queue
		    , workdiv
		    , testGeo_G
		    , get_geoPtr()
		    , 14, 0, 32);
  alpaka::wait(queue);

  std::cout << "TesGeo finished " << std::endl;

  long long* c   = m_regions[14].cell_grid();
  int        np  = m_regions[14].cell_grid_phi();
  int        ne  = m_regions[14].cell_grid_eta();
  int        idx = c[0 * np + 32];
  Identifier Id  = m_cellid_array[idx];
  std::cout << "From Host: Region[14]Grid[0][32]: index=" << idx << ", ID=" << Id
            << ", HashCPU=" << ( *m_cells )[Id]->calo_hash() << ", neta=" << ne << ",  nphi=" << np
            << ", eta=" << ( *m_cells )[Id]->eta() << std::endl;

  return true;
  // end test
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
bool GeoLoadGpu::SanityCheck() {
  // sanity check/test
  QueueAcc queue(alpaka::getDevByIdx<Acc>(Idx{0}));

  WorkDiv workdiv(Idx{1},Idx{1},Idx{1});
  TestHelloKernel testHello;
  alpaka::exec<Acc>(queue
		    , workdiv
		    , testHello);
  TestCellKernel testCell;
  alpaka::exec<Acc>(queue
		    , workdiv
		    , testCell
		    , m_cells_d
		    , 1872);
  alpaka::wait(queue);

  std::cout << " ID of 2000's cell " << m_cellid_array[2000] << std::endl;
  Identifier Id = m_cellid_array[2000];
  std::cout << "ID of cell 2000: " << ( *m_cells )[Id]->identify() << "hashid: " << ( *m_cells )[Id]->calo_hash()
            << std::endl;
  std::cout << "Size of Identify: " << sizeof( Identifier ) << "size of Region: " << sizeof( GeoRegion ) << std::endl;

  std::cout << "GPU Kernel cell test lauched" << std::endl;

  return true;
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
GeoGpu *GeoLoadGpu::Geo_g;
unsigned long GeoLoadGpu::num_cells;

/**
 * Returns a pointer to the sample index buffer on the host device.
 *
 * @return Pointer to the sample index buffer
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
Rg_Sample_Index* GeoLoadGpu::get_sample_index_h_al()
{
  if(!pImpl) pImpl = new Impl();

  pImpl->sample_index_buf_host = alpaka::allocBuf<Rg_Sample_Index, Idx>(alpaka::getDevByIdx<Host>(0u), static_cast<Idx>(m_max_sample));
  return (Rg_Sample_Index*)alpaka::getPtrNative(pImpl->sample_index_buf_host);
}

/**
 * Returns a pointer to the regions buffer on the host device.
 *
 * @return Pointer to the regions buffer
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
GeoRegion* GeoLoadGpu::get_regions_al()
{
  if(!pImpl) pImpl = new Impl();

  pImpl->regions_buf_host = alpaka::allocBuf<GeoRegion, Idx>(alpaka::getDevByIdx<Host>(0u), Idx{m_nregions});
  return (GeoRegion*)alpaka::getPtrNative(pImpl->regions_buf_host);
}

/**
 * Returns a pointer to a grid of cell indices on the GPU
 * @param neta number of eta bins
 * @param nphi number of phi bins
 * @return pointer to cell grid data
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
long long* GeoLoadGpu::get_cell_grid_al(int neta, int nphi)
{
  if(!pImpl) pImpl = new Impl();

  BufHostLongLong cells = alpaka::allocBuf<long long, Idx>(alpaka::getDevByIdx<Host>(0u), static_cast<Idx>(neta*nphi));
  pImpl->reg_vec_host.push_back(cells);
  return (long long*)alpaka::getPtrNative(cells);
}

/**
 * @brief Loads geometry onto the GPU.
 *
 * This function checks if the geometry is empty and returns false if it is.
 * It then allocates device memory for cells and copies the cells from the host to the device.
 * Additionally, it allocates memory for regions and samples, and copies these to the device as well.
 * Finally, it sets up the GeoGpu structure with the allocated memory pointers and returns true upon success.
 *
 * @return True if the geometry was successfully loaded onto the GPU, false otherwise.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
bool GeoLoadGpu::LoadGpu_al() {
  if ( !m_cells || m_ncells == 0 ) {
    std::cout << "Geometry is empty " << std::endl;
    return false;
  }

  if(!pImpl) pImpl = new Impl();

  auto dev = alpaka::getDevByIdx<Acc>(Idx{0});
  std::cout << "Executing on GPU: " << alpaka::getName(dev) << std::endl;

  QueueAcc queue(dev);
  
  BufHostGeoGpu geo_gpu_host = alpaka::allocBuf<GeoGpu,Idx>(alpaka::getDevByIdx<Host>(0u),Idx{1});
  GeoGpu* geo_gpu_ptr = alpaka::getPtrNative(geo_gpu_host);
  num_cells = m_ncells;

  // Allocate Device memory for cells and copy cells as array
  // move cells on host to a array first
  pImpl->cells_buf_acc = alpaka::allocBuf<CaloDetDescrElement, Idx>(alpaka::getDevByIdx<Acc>(0u), m_ncells);
  m_cells_d = alpaka::getPtrNative(pImpl->cells_buf_acc);

  std::cout << "device Malloc " << m_ncells << " cells" << std::endl;

  BufHostCaloDDE cells_buf_host = alpaka::allocBuf<CaloDetDescrElement, Idx>(alpaka::getDevByIdx<Host>(0u),m_ncells);
  CaloDetDescrElement* cells_Host = alpaka::getPtrNative(cells_buf_host);

  m_cellid_array                  = (Identifier*)malloc(m_ncells*sizeof(Identifier));

  // create an array of cell identities, they are in order of hashids.
  int ii = 0;
  for(t_cellmap::iterator ic = m_cells->begin(); ic != m_cells->end(); ++ic) {
    cells_Host[ii]     = *( *ic ).second;
    Identifier id      = ( ( *ic ).second )->identify();
    m_cellid_array[ii] = id;
    ii++;
  }

  alpaka::memcpy(queue,pImpl->cells_buf_acc,cells_buf_host);
  alpaka::wait(queue);
  
  std::cout << "device Memcpy " << ii << "/" << m_ncells << " cells"
            << " Total:" << ii * sizeof( CaloDetDescrElement ) << " Bytes" << std::endl;

  if ( 0 ) {
    if ( !SanityCheck() ) { return false; }
  }

  pImpl->sample_index_buf_acc = alpaka::allocBuf<Rg_Sample_Index, Idx>(alpaka::getDevByIdx<Acc>(0u), static_cast<Idx>(m_max_sample));
  Rg_Sample_Index* SampleIndex_g = alpaka::getPtrNative(pImpl->sample_index_buf_acc);

  // copy sample_index array  to gpu
  alpaka::memcpy(queue,pImpl->sample_index_buf_acc,pImpl->sample_index_buf_host);
  alpaka::wait(queue);

  // each Region allocate a grid (long Long) gpu array
  //  copy array to GPU
  //  save to regions m_cell_g ;
  for(unsigned int ir = 0; ir < m_nregions; ++ir) {
    BufAccLongLong gv = alpaka::allocBuf<long long, Idx>(alpaka::getDevByIdx<Acc>(0u), static_cast<Idx>(m_regions[ir].cell_grid_eta()* m_regions[ir].cell_grid_phi()));
    pImpl->reg_vec_acc.push_back(gv);
    long long* ptr_g = alpaka::getPtrNative(gv);

    alpaka::memcpy(queue,gv,pImpl->reg_vec_host[ir]);
    alpaka::wait(queue);

    m_regions[ir].set_cell_grid_g( ptr_g );
    m_regions[ir].set_all_cells( m_cells_d ); // set this so all region instance know where the GPU cells are, before copy to GPU
  }

  // GPU allocate Regions data  and load them to GPU as array of regions

  pImpl->regions_buf_acc = alpaka::allocBuf<GeoRegion,Idx>(alpaka::getDevByIdx<Acc>(0u), Idx{m_nregions});
  m_regions_d = alpaka::getPtrNative(pImpl->regions_buf_acc);

  alpaka::memcpy(queue,pImpl->regions_buf_acc,pImpl->regions_buf_host);

  geo_gpu_ptr->cells        = m_cells_d;
  geo_gpu_ptr->ncells       = m_ncells;
  geo_gpu_ptr->nregions     = m_nregions;
  geo_gpu_ptr->regions      = m_regions_d;
  geo_gpu_ptr->max_sample   = m_max_sample;
  geo_gpu_ptr->sample_index = SampleIndex_g;


  std::cout << "alpaka GEO\n";
  std::cout << "ncells: " << geo_gpu_ptr->ncells << "\n";
  std::cout << "regions: " << m_nregions << "\n";
  std::cout << "=================================\n";
  
  // Now copy this to GPU and set the static member to this pointer
  pImpl->geogpu_buf_acc = alpaka::allocBuf<GeoGpu,Idx>(alpaka::getDevByIdx<Acc>(0u), Idx{sizeof(GeoGpu)});
  GeoGpu* Gptr = alpaka::getPtrNative(pImpl->geogpu_buf_acc);

  alpaka::memcpy(queue,pImpl->geogpu_buf_acc,geo_gpu_host);
  alpaka::wait(queue);
  
  m_geo_d = Gptr;
  Geo_g = Gptr;

  // more test for region grids
  if ( 0 ) { return TestGeo(); }
  return true;
}

