/*
  Copyright (C) 2002-2021 CERN for the benefit of the ATLAS collaboration
*/

#include "GeoLoadGpu.h"

/**
 * Loads GPU resources according to selected parallelization method
 *
 * @return true if loading is successful false otherwise
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
bool GeoLoadGpu::LoadGpu() {

#if defined(USE_STDPAR)
  return LoadGpu_sp();
#elif defined(USE_KOKKOS)
  return LoadGpu_kk();
#elif defined(USE_ALPAKA)
  return LoadGpu_al();
#elif defined(USE_OMPGPU)
  return LoadGpu_omp();
#else
  return LoadGpu_cu();
#endif
}

/**
 * Returns a sample index handle for GPU operations.
 *
 * @return Rg_Sample_Index pointer to sample index handle
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
Rg_Sample_Index* GeoLoadGpu::get_sample_index_h() {
#if defined(USE_ALPAKA)
  return get_sample_index_h_al();
#else
  return nullptr;
#endif
}

/**
 * Returns a list of geographic regions loaded on the GPU.
 *
 * @return Pointer to a GeoRegion object containing the loaded regions
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
GeoRegion* GeoLoadGpu::get_regions() {
#if defined(USE_ALPAKA)
  return get_regions_al();
#else
  return nullptr;
#endif
}

/**
 * Returns a pointer to the cell grid data structure on the GPU.
 *
 * @param neta Number of eta bins in the grid
 * @param nphi Number of phi bins in the grid
 * @return Pointer to the cell grid data structure or null if not supported
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
long long* GeoLoadGpu::get_cell_grid(int neta, int nphi)
{
#if defined(USE_ALPAKA)
  return get_cell_grid_al(neta, nphi);
#else
  return nullptr;
#endif
}
