/*
  Copyright (C) 2002-2021 CERN for the benefit of the ATLAS collaboration
*/

#include "gpuQ.h"
#include <iostream>

/**
 * @brief Checks the status of a HIP operation and terminates execution upon error
 * @param code The result of a HIP operation
 * @param file The filename where the assertion was triggered
 * @param line The line number where the assertion was triggered
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
void gpu_assert(hipError_t code, const char *file, const int line) {
  if (code != hipSuccess) {
    std::cerr << "gpu_assert: " << hipGetErrorString(code) << " " << file
              << " " << line << std::endl;
    exit(code);
  }
}
