/*
  Copyright (C) 2002-2021 CERN for the benefit of the ATLAS collaboration
*/

#include <random>
#include <vector>
#include <algorithm>

#define cpu_randgen_t std::mt19937

/**
 * Creates a CPU-based random number generator with the given seed value.
 *
 * @param seed The initial seed value for the random number generator.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
void Rand4Hits::createCPUGen(unsigned long long seed) {
  cpu_randgen_t *eng = new cpu_randgen_t(seed);
  m_gen = (void *)eng;
}

/**
 * Destroys the CPU random number generator.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
void Rand4Hits::destroyCPUGen() {
  if (m_gen) {
    delete (cpu_randgen_t *)m_gen;
  }
  //  if ( m_rnd_cpu ) { delete (m_rnd_cpu); }
}

/**
 * Generates an array of random floating point numbers on the CPU.
 *
 * @param num The number of random numbers to generate.
 *
 * @return A pointer to the generated array of random numbers.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
float *Rand4Hits::genCPU(size_t num) {

  m_rnd_cpu->resize(num);

  cpu_randgen_t *eng = (cpu_randgen_t *)(m_gen);

  auto RNG = [eng](float low, float high) {
    auto randomFunc = [
      distribution_ = std::uniform_real_distribution<float>(low, high),
      random_engine_ = *eng
    ]() mutable {
      return distribution_(random_engine_);
    };
    return randomFunc;
  };

  std::generate_n(m_rnd_cpu->begin(), num, RNG(0.f, 1.f));

  return m_rnd_cpu->data();
}
