/*
  Copyright (C) 2002-2019 CERN for the benefit of the ATLAS collaboration
*/

#include "SampleInfo.h"

namespace FCS {

/**
 * Outputs DSIDInfo object to ostream
 *
 * @param out reference to output stream
 * @param info constant reference to DSIDInfo object
 * @return reference to output stream
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
std::ostream &operator<<(std::ostream &out,
                         const DSIDInfo &info)
{
    out << "DSID: " << info.dsid << "\t";
    out << "PDG ID: " << info.pdgId << "\t";
    out << "Energy: " << info.energy << "\t";
    out << "Eta: " << info.eta << "\t";
    out << "Z: " << info.zVertex << "\t";

    return out;
  }

/**
 * Outputs SampleInfo object to ostream
 *
 * @param[out] out   reference to output stream
 * @param[in]  info  constant reference to SampleInfo object
 * @return reference to output stream
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
std::ostream &operator<<(std::ostream &out,
                         const SampleInfo &info)
{
    out << "DSID: " << info.dsid << "\t";
    out << "Location: " << info.location << "\t";

    return out;
  }

} // namespace FCS
