/*
  Copyright (C) 2002-2018 CERN for the benefit of the ATLAS collaboration
*/

#include <fstream>
#include <iostream>
#include <sstream>

#include "TFCSSampleDiscovery.h"

std::string TFCSSampleDiscovery::m_baseDir = "";

/**
 * Constructor for the class 
 * Initializes member variables and checks if base directory is set
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
TFCSSampleDiscovery::TFCSSampleDiscovery() :
  m_invalid( FCS::DSIDInfo( -1 ) ) {

  if (m_baseDir == "") {
    throw std::runtime_error("DataDir not set for input files either via arg or env var");
  }

}

/**
 * Constructor for TFCSSampleDiscovery class.
 *
 * @param dir        Directory path where input files are located.
 * @param fileName  Name of the file containing DSID database information.
 * @param debug     Flag indicating whether to print debugging output.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
TFCSSampleDiscovery::TFCSSampleDiscovery(const std::string& dir, const std::string& fileName,
                                         bool debug)
  : m_invalid(FCS::DSIDInfo(-1)), m_dsidDB(fileName) {

  m_baseDir = dir;

  std::cout << "Reading input files from " << m_baseDir << std::endl;
  std::cout << "Initialising DSID DB..." << std::endl;

  // init the DB
  std::ifstream file = openFile( fileName );
  if ( !file ) {
    std::cerr << "DB initialisation failed: " << fileName << " not found :((("
              << std::endl;
    exit( 1 );
  }

  std::string line;
  while ( getline( file, line ) ) {
    std::stringstream linestream( line );
    int               pdgId, energy, z, dsid;
    float             eta;
    linestream >> pdgId >> energy >> eta >> z >> dsid;

    m_dbDSID.emplace_back( dsid, pdgId, energy, eta, z );
  }

  if ( debug ) {
    for (const FCS::DSIDInfo &info : m_dbDSID) {
      std::cout << info << std::endl;
    }
  }

  std::cout << "DB ready" << std::endl;
}

/**
 * Finds the DSID information that matches the specified particle ID, energy, eta, and z vertex.
 *
 * @param pdgId   The particle ID to search for.
 * @param energy The energy value to match.
 * @param eta    The eta value to match.
 * @param zVertex The z vertex value to match.
 *
 * @return A reference to the matching DSID information, or an invalid DSID object if no match is found.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
const FCS::DSIDInfo &TFCSSampleDiscovery::findDSID(int pdgId, int energy,
                                                   float eta, int zVertex) const
{
  for ( const FCS::DSIDInfo& info : m_dbDSID ) {
    if (pdgId == info.pdgId && energy == info.energy && eta == info.eta &&
        zVertex == info.zVertex) {
      return info;
    }
  }

  std::cerr << " Error: no DSID matching pid " << pdgId << " energy " << energy
            << " eta " << eta << " zVertex " << zVertex << " found in DSID DB \'"
            << m_dsidDB << "\'" << std::endl;
  
  return m_invalid;
}

/**
 * Returns the energy associated with a given Data Set ID.
 *
 * @param dsid The Data Set ID to retrieve the energy for.
 * @return The energy value corresponding to the specified Data Set ID, or 0 if not found.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
int TFCSSampleDiscovery::getEnergy(int dsid) const
{
  for ( const FCS::DSIDInfo& info : m_dbDSID ) {
    if (info.dsid == dsid) {
      return info.energy;
    }
  }

  return 0;
}

/**
 * Retrieves the particle data group ID associated with a given dataset ID.
 *
 * @param dsid The dataset ID to look up.
 * @return The corresponding particle data group ID if found, -1 otherwise.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
int TFCSSampleDiscovery::getPdgId(int dsid) const
{
  for ( const FCS::DSIDInfo& info : m_dbDSID ) {
    if (info.dsid == dsid) {
      return info.pdgId;
    }
  }

  return -1;
}

/**
 * Finds sample information from an input file based on the given dataset ID.
 *
 * @param[in] inDSID   The dataset ID to search for in the input file.
 * @param[in] fileName The name of the input file containing sample data.
 *
 * @return A SampleInfo object containing the details of the matching sample,
 *         or a default-constructed SampleInfo object if no match is found.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
FCS::SampleInfo TFCSSampleDiscovery::findSample(int inDSID, const std::string &fileName) const {
  int         dsid, pdgId, energy, zVertex;
  std::string location, label;
  float       etaMin, etaMax;

  std::ifstream file = openFile(fileName);
  if (!file) {
    std::cerr << " Error: Unable to open file \'" << fileName
              << "\' with input samples data" << std::endl;
    exit(1);
  }

  while ( !file.eof() ) {
    file >> dsid >> location >> label >> pdgId >> energy
          >> etaMin >> etaMax >> zVertex;

    if ( dsid == inDSID ) {
      return FCS::SampleInfo( dsid, m_baseDir + "/" + FCS::DIR_INPUTS + location, label,
                              pdgId, energy, etaMin, etaMax, zVertex );
    }
  }

  std::cerr << " Error: DSID " << inDSID << " not found in input sample file \'"
            << fileName << "\'" << std::endl;
  
  return FCS::SampleInfo(-1);
}

/**
 * Returns the base name of a sample discovery dataset.
 *
 * @param dsid The ID of the dataset.
 * @return A string representing the base name of the dataset.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
std::string TFCSSampleDiscovery::getBaseName(int dsid) const
{
  for ( const FCS::DSIDInfo& info : m_dbDSID ) {
    if ( info.dsid == dsid ) {
      std::stringstream s;
      s << "mc16_13TeV." << dsid << ".ParticleGun_pid" << info.pdgId
        << "_E" << info.energy << "_disj_eta_m" << (info.eta + 5)
        << "_m" << info.eta << "_" << info.eta << "_"
        << (info.eta + 5) << "_zv_" << info.zVertex;
      return s.str();
    }
  }

  return "";
}

/**
 * Returns the first PCA application name for a given data source ID and version.
 *
 * @param dsid Data source ID
 * @param version Version string
 * @return First PCA application name as a string
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
std::string TFCSSampleDiscovery::getFirstPCAAppName(int dsid,
                                                    const std::string &version) const {
  return getName( dsid, "firstPCA_App", m_baseDir + "/" + FCS::DIR_FIRSTPCA, version );
}

/**
 * Returns the second PCA name for the specified dataset identifier and version.
 *
 * @param dsid The dataset identifier.
 * @param version The version string.
 * @return The second PCA name as a string.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
std::string TFCSSampleDiscovery::getSecondPCAName(int dsid,
                                                  const std::string &version) const
{
  return getName( dsid, "secondPCA", m_baseDir + "/" + FCS::DIR_DSID, version );
}

/**
 * Returns the shape name associated with the given data set ID and version.
 *
 * @param dsid The data set ID.
 * @param version The version of the shape.
 * @return The shape name as a string.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
std::string TFCSSampleDiscovery::getShapeName(int dsid,
                                              const std::string &version) const
{
  return getName( dsid, "shapepara", m_baseDir + "/" + FCS::DIR_DSID, version );
}

/**
 * Returns the average simulated shape name for a given data set ID and version.
 *
 * @param dsid Data set ID
 * @param version Version of the simulation
 * @return Average simulated shape name as a string
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
std::string TFCSSampleDiscovery::getAvgSimShapeName(int dsid,
                                                    const std::string &version) const
{
  return getName( dsid, "AvgSimShape", m_baseDir + "/" + FCS::DIR_DSID, version );
}

/**
 * Returns the mean energy interpolation file name for a given particle data group ID and version.
 *
 * @param pdgId Particle Data Group ID
 * @param version Version of the interpolation file
 * @return Mean energy interpolation file name as a string
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
std::string TFCSSampleDiscovery::getEinterpolMeanName(int pdgId,
                                                      const std::string &version) const
{
  return m_baseDir + "/" + FCS::DIR_INTERPOLATION + "mc16_13TeV.pid" + std::to_string( pdgId ) + ".EinterpolMean." + version + ".root";
}

/**
 * Returns the parametrization file name for a given version.
 *
 * @param version The version number of the parametrization file.
 * @return The full path of the parametrization file.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
std::string TFCSSampleDiscovery::getParametrizationName(const std::string &version)
{
  return m_baseDir + "/" + FCS::DIR_PARAMETRIZATION  + "TFCSparam_" + version + ".root";
}

/**
 * Returns the wiggle file name based on the input parameters.
 *
 * @param etaRange The eta range of the wiggle file.
 * @param sampling The sampling value of the wiggle file.
 * @param isNewWiggle Flag indicating whether it is a new wiggle file.
 * @param version The version of the wiggle file.
 * @return The full path of the wiggle file.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
std::string TFCSSampleDiscovery::getWiggleName(const std::string &etaRange,
                                               int sampling,
                                               bool isNewWiggle,
                                               const std::string &version)
{
  if ( isNewWiggle ) {
    return m_baseDir + "/" + FCS::DIR_WIGGLE + "Wiggle/" + etaRange + "." + version + ".root";
  } else {
    return m_baseDir + "/" + FCS::DIR_WIGGLE + "Wiggle_old/" + etaRange +
      "/wiggle_input_deriv_Sampling_" + std::to_string( sampling ) + ".ver03.root";    
  }
}

/**
 * Returns the geometry tree of the sample discovery.
 *
 * @return The geometry tree as a string.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
std::string TFCSSampleDiscovery::geometryTree()
{
  return "ATLAS-R2-2016-01-00-01";
}

/**
 * Returns the geometry file name for the sample discovery.
 *
 * @return The full path of the geometry file.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
std::string TFCSSampleDiscovery::geometryName()
{
  return m_baseDir + "/" + FCS::DIR_GEOMETRY + "Geometry-ATLAS-R2-2016-01-00-01.root";
}

/**
 * Returns an array of geometry file names for FCal 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
std::array<std::string, 3> TFCSSampleDiscovery::geometryNameFCal() {
  return {
    m_baseDir + "/" + FCS::DIR_GEOMETRY + "FCal1-electrodes.sorted.HV.09Nov2007.dat",
    m_baseDir + "/" + FCS::DIR_GEOMETRY + "FCal2-electrodes.sorted.HV.April2011.dat",
    m_baseDir + "/" + FCS::DIR_GEOMETRY + "FCal3-electrodes.sorted.HV.09Nov2007.dat",
  };
}

std::string TFCSSampleDiscovery::geometryMap() {
  return m_baseDir + "/" + FCS::DIR_GEOMETRY + "cellId_vs_cellHashId_map.txt";
}

/**
 * Opens a file specified by its filename, attempting to find it in the current directory 
 * and then in a designated data folder if necessary.
 *
 * @param fileName The name of the file to be opened.
 * @return An input file stream object associated with the opened file.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
std::ifstream TFCSSampleDiscovery::openFile(const std::string &fileName) const
{
  // first try directly
  std::ifstream file( fileName );
  // if not found try common data folder
  if ( !file && fileName.find( "/" ) == std::string::npos ) {
    std::string path = std::getenv( "FCSSTANDALONE" );
    return std::ifstream( path + "/data/" + fileName );
  }

  return file;
}

/**
 * Returns the full file path of a sample discovery file.
 *
 * @param dsid        dataset identifier
 * @param label      sample label
 * @param basedir    base directory path
 * @param version   version string
 * @return full file path as a string
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
std::string TFCSSampleDiscovery::getName(int dsid, const std::string &label,
                                         const std::string &basedir,
                                          const std::string& version ) const {
  return basedir + getBaseName( dsid ) + "." + label + "." + version + ".root";
}
