//
//  docopt_util.h
//  docopt
//
//  Created by Jared Grubb on 2013-11-04.
//  Copyright (c) 2013 Jared Grubb. All rights reserved.
//

#ifndef docopt_docopt_util_h
#define docopt_docopt_util_h

#if DOCTOPT_USE_BOOST_REGEX
#  include <boost/regex.hpp>
namespace std {
  using boost::regex;
  using boost::sregex_token_iterator;
}
#else
#  include <regex>
#endif

#if 0
#  pragma mark -
#  pragma mark General utility
#endif

namespace {
/**
 * Checks if a string starts with a specified prefix.
 *
 * @param str The input string to check.
 * @param prefix The prefix to search for at the start of the string.
 * @return True if the string starts with the prefix, false otherwise.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
	bool starts_with(std::string const& str, std::string const& prefix)
	{
		if (str.length() < prefix.length())
			return false;
		return std::equal(prefix.begin(), prefix.end(),
				  str.begin());
  }

/**
 * Removes leading and trailing whitespace from a string
 *
 * @param str The input string to be trimmed
 * @param whitespace The set of whitespace characters to remove defaults to space tab newline
 * @return The trimmed string
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
	std::string trim(std::string&& str,
			 const std::string& whitespace = " \t\n")
	{
    const auto strEnd = str.find_last_not_of( whitespace );
		if (strEnd==std::string::npos)
			return {}; // no content
    str.erase( strEnd + 1 );

    const auto strBegin = str.find_first_not_of( whitespace );
    str.erase( 0, strBegin );

    return std::move( str );
  }

/**
 * Splits a string into substrings separated by spaces
 *
 * @param str The input string to be split
 * @param pos The starting position in the string
 * @return A vector of substrings
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
	std::vector<std::string> split(std::string const& str, size_t pos = 0)
	{
    const char* const anySpace = " \t\r\n\v\f";

    std::vector<std::string> ret;
    while ( pos != std::string::npos ) {
      auto start = str.find_first_not_of( anySpace, pos );
      if ( start == std::string::npos ) break;

      auto end  = str.find_first_of( anySpace, start );
      auto size = end == std::string::npos ? end : end - start;
      ret.emplace_back( str.substr( start, size ) );

      pos = end;
    }

    return ret;
  }

/**
 * Function to partition a given string around a specified point
 * @param str The input string to be partitioned
 * @param point The point around which the string is to be partitioned
 * @return A tuple containing three strings representing the partitioned parts of the input string
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
	std::tuple<std::string, std::string, std::string> partition(std::string str, std::string const& point)
	{
    std::tuple<std::string, std::string, std::string> ret;

    auto i = str.find( point );

    if ( i == std::string::npos ) {
      // no match: string goes in 0th spot only
    } else {
      std::get<2>( ret ) = str.substr( i + point.size() );
      std::get<1>( ret ) = point;
      str.resize( i );
    }
    std::get<0>( ret ) = std::move( str );

    return ret;
  }

  template <typename I>
/**
 * Function to concatenate all elements in a range with a specified delimiter
 * @param iter   beginning of the range
 * @param end    end of the range
 * @param delim  string used as separator between elements
 * @return concatenated string
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  std::string join( I iter, I end, std::string const& delim ) {
		if (iter==end)
			return {};

    std::string ret = *iter;
    for ( ++iter; iter != end; ++iter ) {
      ret.append( delim );
      ret.append( *iter );
    }
    return ret;
  }

/**
 * Splits a string into substrings based on a regular expression.
 *
 * @param text The input string to be split.
 * @param re The regular expression used for splitting.
 * @return A vector of strings representing the split substrings.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
	std::vector<std::string> regex_split(std::string const& text, std::regex const& re)
	{
    std::vector<std::string> ret;
		for (auto it = std::sregex_token_iterator(text.begin(), text.end(), re, -1);
			it != std::sregex_token_iterator();
          ++it ) {
      ret.emplace_back( *it );
    }
    return ret;
  }
}

namespace docopt {
  template <class T>
/**
 * Combines two hash values into a single hash value.
 *
 * @param seed The initial hash value to be combined with.
 * @param v The value to combine with the initial hash value.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
	inline void hash_combine(std::size_t& seed, T const& v)
	{
    // stolen from boost::hash_combine
    std::hash<T> hasher;
    seed ^= hasher( v ) + 0x9e3779b9 + ( seed << 6 ) + ( seed >> 2 );
  }
}

#endif
