/*
  Copyright (C) 2002-2021 CERN for the benefit of the ATLAS collaboration
*/

#include "HepPDT/ParticleID.hh"

#include <cmath>
#include <iostream>
#include <limits>

namespace HepPDT
{

/**
 * Constructor for ParticleID class with particle data number identifier
 * @param pdgID particle data number identifier
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
ParticleID::ParticleID(const int pdgID)
{
    if ( pdgID == 11 || pdgID == 211 || pdgID == 2212 )
      m_charge = 1.;
    else if ( pdgID == -11 || pdgID == -211 || pdgID == -2212 )
      m_charge = -1.;
    else if ( pdgID == 22 || std::abs( pdgID ) == 2112 || pdgID == 111 )
      m_charge = 0;
    else {
      std::cerr << "Error: This pdgID is not supported: " << std::endl;
      m_charge = std::numeric_limits<double>::quiet_NaN();
    }
  }

} // namespace HepPDT
