/*
  Copyright (C) 2002-2021 CERN for the benefit of the ATLAS collaboration
*/

#ifndef TFCSEnergyParametrizationPCABinCalculator_h
#define TFCSEnergyParametrizationPCABinCalculator_h

//#include "ISF_FastCaloSimEvent/TFCSParametrization.h"
#include "ISF_FastCaloSimEvent/TFCSEnergyParametrization.h"
#include "ISF_FastCaloSimEvent/TFCSSimulationState.h"
#include "TFCSApplyFirstPCA.h"


/**
 * @class TFCSEnergyParametrizationPCABinCalculator
 * @brief Calculator for energy parametrization using PCA binning
 * @details This class provides functionality for simulating energy parametrization
 *          using Principal Component Analysis (PCA) binning
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
class TFCSEnergyParametrizationPCABinCalculator: public TFCSEnergyParametrization
{

public:

    TFCSEnergyParametrizationPCABinCalculator(TFCSApplyFirstPCA applyfirstPCA, const char* name = nullptr, const char* title = nullptr);

    virtual FCSReturnCode simulate(TFCSSimulationState& simulstate, const TFCSTruthState* truth, const TFCSExtrapolationState* extrapol) override;

  int PCAbin() { return m_PCAbin; }

private:
  TFCSApplyFirstPCA m_applyfirstPCA;

  int m_PCAbin;

  ClassDefOverride( TFCSEnergyParametrizationPCABinCalculator, 1 ) // TFCSEnergyParametrizationPCABinCalculator
};

#if defined( __ROOTCLING__ ) && defined( __FastCaloSimStandAlone__ )
#  pragma link C++ class TFCSEnergyParametrizationPCABinCalculator + ;
#endif

#endif
