/*
  Copyright (C) 2002-2018 CERN for the benefit of the ATLAS collaboration
 */

#include "CLHEP/Random/RandPoisson.h"

namespace CLHEP {

/**
 * Generates a random number from a Poisson distribution with the given mean.
 *
 * @param engine Pointer to HepRandomEngine instance
 * @param mean Mean value of the Poisson distribution
 * @return Randomly generated number from the Poisson distribution
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
double RandPoisson::shoot(HepRandomEngine *engine, double mean)
{
  return engine->poisson(mean);
}

} // namespace CLHEP
