/*
  Copyright (C) 2002-2018 CERN for the benefit of the ATLAS collaboration
 */

#include "CLHEP/Random/RandGauss.h"

namespace CLHEP {

/**
 * Generates a random number from a Gaussian distribution.
 *
 * @param engine   HepRandomEngine instance used to generate the random number
 * @param mean     Mean value of the Gaussian distribution
 * @param stdDev   Standard deviation of the Gaussian distribution
 * @return        A random number from the Gaussian distribution
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
double RandGauss::shoot(HepRandomEngine *engine, double mean, double stdDev)
{
    return engine->gauss( mean, stdDev );
  }

} // namespace CLHEP
