/*
  Copyright (C) 2002-2018 CERN for the benefit of the ATLAS collaboration
 */

#include "CLHEP/Random/RandFlat.h"

namespace CLHEP {

/**

 * Returns a random number generated by the provided HepRandomEngine
 * 
 * @param engine Pointer to the HepRandomEngine used for generating the random number
 * @return A random number
 */
// The above comment was written by an LLM. 
double RandFlat::shoot(HepRandomEngine *engine)
{
  return engine->random();
}

/**

 * Generates a random double precision floating point number within a specified range
 * @param engine HepRandomEngine object used to generate the random number
 * @param a lower bound of the range inclusive
 * @param b upper bound of the range inclusive
 * @return a random double precision floating point number between a and b
 */
// The above comment was written by an LLM. 
double RandFlat::shoot(HepRandomEngine *engine, double a, double b)
{
  return (b - a) * engine->random() + a;
}

/**

 * Generates a random double value within a specified range
 * @param engine HepRandomEngine object used for generating random numbers
 * @param width Range of the random values to be generated
 * @return A random double value between 0 and width
 */
// The above comment was written by an LLM. 
double RandFlat::shoot(HepRandomEngine *engine, double width)
{
  return width * engine->random();
}

} // namespace CLHEP
