/*
  Copyright (C) 2002-2018 CERN for the benefit of the ATLAS collaboration
 */

#include <TRandom3.h>

#include "CLHEP/Random/TRandomEngine.h"

namespace CLHEP {

/**
 * Constructor for the TRandomEngine class initializing the random number generator
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
TRandomEngine::TRandomEngine()
  : HepRandomEngine()
{
  m_random = new TRandom3(42);
}

/**
 * Destructor for TRandomEngine class 
 * Releases dynamically allocated memory for random number generator
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
TRandomEngine::~TRandomEngine()
{
  delete m_random;
}

/**
 * Sets the seed value for the random number generator
 * @param seed the new seed value
 * @param unused integer parameter
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
void TRandomEngine::setSeed(long seed, int)
{
  m_random->SetSeed(seed);
}

/**
 * Returns a random number in the range [0,1)
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
double TRandomEngine::random()
{
    // The use of 1 - engine->Rndm() is a fudge for TRandom3, as it generates random numbers
    // in (0,1], but [0,1) or (0,1) is needed.
    return 1 - m_random->Rndm();
  }

/**
 * Generates a random number from a Gaussian distribution
 * @param mean the mean of the Gaussian distribution
 * @param stdDev the standard deviation of the Gaussian distribution
 * @return a random number from the Gaussian distribution
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
double TRandomEngine::gauss(double mean, double stdDev)
{
  return m_random->Gaus(mean, stdDev);
}

/**
 * Generates a Poisson distributed random number with the given mean
 * @param mean the mean of the Poisson distribution
 * @return a random number following the Poisson distribution
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
double TRandomEngine::poisson(double mean)
{
  return m_random->Poisson(mean);
}

} // namespace CLHEP
